apiVersion: v1
kind: Service
metadata:
  name: fastapi-k8s-hello-world-service
spec:
  selector:
    app: fastapi-k8s-hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
